prancing/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import DetailView, ListView

from productos.models import Venta
from haberes.models import Liquidacion
from gente.models import Huesped


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^productos/producto/(?P<codigo_producto>\d+)/ajax/precio_unitario/$',
        'productos.views.ajax_precio_unitario',
        name='productos_ajax_precio_unitario'),
    url(r'^productos/insumo/(?P<codigo_insumo>\d+)/ajax/precio_de_costo/$',
        'productos.views.ajax_precio_de_costo',
        name='productos_ajax_precio_de_costo'),
    url(r'^hospedaje/reserva/(?P<id_reserva>\d+)/ajax/$',
        'hospedaje.views.datos_reserva', name='hospedaje_reserva_ajax'),
    url(r'^hospedaje/alquiler/(?P<id_alquiler>\d+)/ajax/cliente/$',
        'hospedaje.views.ajax_cliente_alquiler',
        name='hospedaje_cliente_alquiler_ajax'),
    url(r'^hospedaje/habitaciones/ajax/disponibles(?:/(?P<form_prefix>[\w\-_]+))?/$',
        'hospedaje.views.habitaciones_disponibles_ajax',
        name='hospedaje_habitaciones_disponibles_ajax'),
    url(r'^hospedaje/categorias/ajax/disponibles(?:/(?P<form_prefix>[\w\-_]+))?/$',
        'hospedaje.views.categorias_disponibles_ajax',
        name='hospedaje_categorias_disponibles_ajax'),
    url(r'^productos/venta/(?P<pk>\d+)/imprimir/$', DetailView.as_view(
        template_name='imprimir_venta.html', model=Venta,
        context_object_name='venta'), name='productos_venta_imprimir'),
    url(r'^haberes/liquidacion/(?P<pk>\d+)/imprimir/$', DetailView.as_view(
        template_name='imprimir_liquidacion.html', model=Liquidacion,
        context_object_name='liquidacion'), name='haberes_liquidacion_imprimir'),
    url(r'^gente/huesped/imprimir/$', ListView.as_view(
        template_name='imprimir_huesped.html', model=Huesped,
        context_object_name='huespedes'), name='hospedaje_huesped_imprimir'),
    url(r'^administracion/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gente/models.py
# -*- coding: utf-8 -*-
from datetime import date

from django.db import models
from django.contrib.auth.models import User
from django.contrib.localflavor.ar.forms import PROVINCE_CHOICES
from django.contrib.admin.models import LogEntry


class PersonaBase(models.Model):
    dni = models.CharField(max_length=8)
    domicilio = models.CharField(max_length=200)
    localidad = models.CharField(max_length=200)
    provincia = models.CharField(max_length=50, choices=PROVINCE_CHOICES)
    telefono = models.CharField(u'Teléfono', max_length=16, blank=True)

    class Meta:
        abstract = True


class PersonaUsuario(PersonaBase):
    user = models.ForeignKey(User, editable=False)

    class Meta(PersonaBase.Meta):
        abstract = True

    @property
    def apellido(self):
        try:
            return self.user.last_name
        except User.DoesNotExist:
            return None

    @apellido.setter
    def apellido(self, valor):
        try:
            self.user.last_name = valor
        except User.DoesNotExist:
            self.user = User(last_name=valor)

    @property
    def nombre(self):
        try:
            return self.user.first_name
        except User.DoesNotExist:
            return None

    @nombre.setter
    def nombre(self, valor):
        try:
            self.user.first_name = valor
        except User.DoesNotExist:
            self.user = User(first_name=valor)

    @property
    def email(self):
        try:
            return self.user.email
        except User.DoesNotExist:
            return None

    @email.setter
    def email(self, valor):
        try:
            self.user.email = valor
        except User.DoesNotExist:
            self.user = User(email=valor)


class PersonaAutonomo(PersonaBase):
    apellido = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    email = models.EmailField(blank=True, null=True)

    class Meta(PersonaBase.Meta):
        abstract = True


OPCIONES_CARGO = (
        ('cocinero', 'Cocinero'),
        ('encargado', 'Encargado'),
        ('mozo', 'Mozo'),
        ('mucama', 'Mucama'),
)


class Cargo(models.Model):
    puesto = models.CharField(max_length=200)
    turno = models.CharField(max_length=30, choices=(
        (u'mañana', u'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')))
    hora_ingreso = models.TimeField()
    hora_salida = models.TimeField()
    sueldo = models.DecimalField(max_digits=15, decimal_places=2)

    def __unicode__(self):
        return u'%s (%s)' % (self.puesto, self.get_turno_display())


class Empleado(PersonaUsuario):
    cuil = models.CharField(max_length=15, unique=True, null=True)
    fecha_ingreso = models.DateField()
    cantidad_de_hijos = models.PositiveSmallIntegerField(default=0)
    cargo = models.ForeignKey(Cargo, null=True, related_name='empleados')

    def __unicode__(self):
        return u'%s, %s (empleado #%d)' % (self.apellido, self.nombre, self.id)

    @property
    def antiguedad(self):
        hoy = date.today()
        return (hoy - self.fecha_ingreso).days / 365

class Cliente(PersonaAutonomo):
    tipo_cliente = models.CharField('Tipo de cliente', max_length=20, default='particular', choices=(
        ('particular', 'Particular'), ('empresa', 'Empresa')))
    cuit_o_cuil = models.CharField(max_length=15, db_index=True)

    def __unicode__(self):
        return u'Cliente %s, %s' % (self.apellido, self.nombre)


class Huesped(PersonaAutonomo):

    class Meta:
        verbose_name_plural = u'Huespedes'

    def __unicode__(self):
        return u'Huesped %s, %s' % (self.apellido, self.nombre)


class Proveedor(PersonaAutonomo):
    cuit = models.CharField(max_length=15, unique=True, db_index=True)

    class Meta:
        verbose_name_plural = u'Proveedores'

    def __unicode__(self):
        return u'%s - %s %s' % (self.cuit, self.apellido, self.nombre)


class RegistroDeActividad(LogEntry):
    class Meta:
        proxy = True
        verbose_name_plural = u'Registros de actividad'

prancing/templates/base.html
<!doctype html>{% load url from future %}
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% if title %}{{ title }} | {% endif %}Hoster&iacute;a ATEP</title>

  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure.css">
  <!--[if lte IE 8]>
          <link rel="stylesheet" href="css/main-grid-old-ie.css">
      <![endif]-->
  <!--[if gt IE 8]><!-->
          <link rel="stylesheet" href="{{ STATIC_URL }}css/main-grid.css">
      <!--<![endif]-->
  <!--[if lte IE 8]>
          <link rel="stylesheet" href="{{ STATIC_URL }}css/layouts/marketing-old-ie.css">
      <![endif]-->
  <!--[if gt IE 8]><!-->
          <link rel="stylesheet" href="{{ STATIC_URL }}css/layouts/marketing.css">
      <!--<![endif]-->

  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  {% block extrahead %}{% endblock %}
</head>

<body>
<div class="header">
  <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
    <a class="pure-menu-heading" href="/">Hoster&iacute;a ATEP</a>
    <ul>
      <li><a href="{% url 'admin:index' %}">Administraci&oacute;n</a></li>
    </ul>
  </div>
</div>

<div class="content-wrapper">
  <div class="content">
    {% block content %}{% endblock %}
  </div>


  <div class="footer l-box is-center">
    {{ autores|join:" | " }}
  </div>

</div>
{% block extrabody %}{% endblock %}

<script src="http://yui.yahooapis.com/3.14.1/build/yui/yui.js"></script>
<script>
YUI().use('node-base', 'node-event-delegate', function (Y) {
    // This just makes sure that the href="#" attached to the <a> elements
    // don't scroll you back up the page.
    Y.one('body').delegate('click', function (e) {
      e.preventDefault();
      }, 'a[href="#"]');
    });
</script>
{% block scripts %}{% endblock %}
</body>
</html>

prancing/templates/imprimir_alquiler.html
<!DOCTYPE html>
<html> 
    <head>
        <link href="//d2c5utp5fpfikz.cloudfront.net/3_1_1/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            <strong>{% now 'd/m/Y' %}</strong>
            <h1>Alquiler</h1>
            {% if alquiler.aprobado_por %}
            <p>Aprobado por: <strong>{{ alquiler.aprobado_por }}</strong></p>
            {% endif %}
            <p>Huespedes: <strong>{{ alquiler.huespedes.count }}</strong></p>
            <p>Ingreso: <strong>{{ alquiler.fecha_ingreso|date:"d/m/Y" }}</strong></p>
            <p>Egreso: <strong>{{ alquiler.fecha_egreso|date:"d/m/Y" }}</strong></p>
            {% if alquiler.modalidad %}
            <p>Modalidad: <strong>{{ alquiler.modalida }}</strong></p>
            {% endif %}

            <table class="table">
                <thead>
                  <tr>
                    <th colspan="2">Habitacion</th>
                    <th>Remuneraciones</th>
                    <th>Descuentos</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td colspan="2">Asignaci&oacute;n por hijo</td>
                    <td>{{ liquidacion.auh }}</td>
                    <td></td>
                  </tr>
                {% for detalle in liquidacion.liquidaciondetalle_set.all %}
                  <tr>
                      <td colspan="2">{{ detalle.concepto.tipo }}</td>
                      {% if detalle.concepto.deduccion %}
                      <td></td>
                      <td>{{ detalle.importe }}</td>
                      {% else %}
                      <td>{{ detalle.importe }}</td>
                      <td></td>
                      {% endif %}
                  </tr>
                {% endfor %}
                    <tr>
                        <td></td>
                        <td><strong>Total</strong></td>
                        <td><strong>${{ liquidacion.total }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>

prancing/templates/imprimir_huesped.html
<!DOCTYPE html>
<html> 
    <head>
        <link href="//d2c5utp5fpfikz.cloudfront.net/3_1_1/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            <h1>Libro de Pasajeros</h1>
            <table class="table">
                <thead>
                  <tr>
                    <th>DNI</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Provincia</th>
                    <th>Localidad</th>
                    <th>Domicilio</th>
                  </thead>
                </thead>
                <tbody>
                {% for huesped in huespedes %}
                    <tr>
                        <td>{{ huesped.dni }}</td>
                        <td>{{ huesped.nombre }}</td>
                        <td>{{ huesped.apellido }}</td>
                        <td>{{ huesped.get_provincia_display }}</td>
                        <td>{{ huesped.localidad }}</td>
                        <td>{{ huesped.domicilio }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>

prancing/templates/imprimir_liquidacion.html
<!DOCTYPE html>
<html> 
    <head>
        <link href="//d2c5utp5fpfikz.cloudfront.net/3_1_1/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            {% now "d/m/Y H:i" %}
            <h1>Liquidaci&oacute;n de Sueldo</h1>
            <div style="width:50%;margin:0 4px;float:left;display:block">
              <p>Periodo Liquidado: <strong>{{ liquidacion.periodo }}</strong></p>
              <p>Tipo de Liquidaci&oacute;n: <strong>{{ liquidacion.tipo|title }}</strong></p>
              {% if liquidacion.usuario %}
              <p>Usuario: <strong>{{ liquidacion.usuario.get_full_name|default:liquidacion.usuario.username }}</strong></p>
              {% endif %}
              <p>Empleado: <strong>{{ liquidacion.empleado }}</strong></p>
              <p>Antigüedad: <strong>{{ liquidacion.antiguedad_empleado }} (año{{ liquidacion.antiguedad_empleado|pluralize }})</strong></p>
            </div>
            <div style="width:44%;padding:0 4px;float:right;display:block;min-height:10em;background-color:#abc">
              {% if liquidacion.notas %}
              <h4>Notas:</h4>
              <p>{{ liquidacion.notas }}</p>
              {% endif %}
            </div>
            <table class="table">
                <thead>
                  <tr>
                    <th colspan="2">Concepto</th>
                    <th>Haberes remunerativos</th>
                    <th>Haberes no remunerativos</th>
                    <th>Descuentos</th>
                  </tr>
                </thead>
                <tbody>
                {% for detalle in liquidacion.liquidaciondetalle_set.all %}
                  <tr>
                      <td colspan="2">{{ detalle.concepto }}</td>
                      {% if detalle.concepto.tipo == 'AUH' %}
                      <td></td>
                      <td>{{ detalle.importe }}</td>
                      <td></td>
                      {% elif detalle.concepto.deduccion %}
                      <td></td>
                      <td></td>
                      <td>{{ detalle.importe }}</td>
                      {% else %}
                      <td>{{ detalle.importe }}</td>
                      <td></td>
                      <td></td>
                      {% endif %}
                  </tr>
                {% endfor %}
                    <tr>
                        <td colspan="2">Sueldo B&aacute;sico</td>
                        <td>${{ liquidacion.basico|floatformat:2 }}</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td colspan="2">Antigüedad</td>
                        <td>{{ liquidacion.total_antiguedad|floatformat:2 }}</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td colspan="2"><strong>Totales</strong></td>
                        <td>{{ liquidacion.basico|add:liquidacion.total_antiguedad|floatformat:2 }}</td>
                        <td>{{ liquidacion.total_no_remunerativos }}</td>
                        <td>{{ liquidacion.total_descuentos }}</td>
                    </tr>
                    <tr>
                        <td colspan="2"><strong>Neto a Cobrar</strong></td>
                        <td><strong>${{ liquidacion.total|floatformat:2 }}</strong></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>

prancing/templates/imprimir_venta.html
<!DOCTYPE html>
<html> 
    <head>
        <link href="//d2c5utp5fpfikz.cloudfront.net/3_1_1/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            <strong>{{ venta.fecha_y_hora }}</strong>
            <h1>Recibo</h1>
            <p>Cliente <strong>{{ venta.cliente }}</strong></p>
            <p>Vendedor <strong>{{ venta.vendedor }}</strong></p>
            <table class="table">
                <thead>
                    <tr><th>Producto</th><th>Cantidad</th><th>Descuento (%)</th><th>Subtotal</th></thead>
                </thead>
                <tbody>
                {% for linea in venta.lineadeventa_set.all %}
                    <tr>
                        <td>{{ linea.producto }}</td>
                        <td>{{ linea.cantidad }}</td>
                        <td>{{ linea.descuento }}</td>
                        <td>${{ linea.subtotal }}</td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td></td><td></td>
                        <td><strong>Total</strong></td>
                        <td><strong>${{ venta.calcular_total }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>